version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk
    deploy:
      replicas: 1
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro

  logstash:
    depends_on:
     - elasticsearch
    image: docker.elastic.co/logstash/logstash-oss:6.2.1
    ports:
      - "5000:5000"
    networks:
      - elk
    deploy:
      replicas: 1
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro

  kibana:
    depends_on:
     - elasticsearch
    image: docker.elastic.co/kibana/kibana-oss:6.2.1
    ports:
      - "5601:5601"
    networks:
      - elk
    deploy:
      replicas: 1
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro

networks:
    elk:
      driver: bridge